### ISSUE TITLE
Any chance of jade support?

### ISSUE THREAD

**Issue by jaylach** [baysao/meteor-riotjs#1]
First off, thanks for this. I like your implementation better than xaiki's, if only because of your RiotData and RiotTemplate modules :)

Is there any chance of getting jade support for tag files? I know riot supports any number of preprocessors, and I have a huge biased towards jade!

Thanks! :)

**Comment by bkuri** [comment]
+1 jade support would be really nice.

FYC: The package `mquandalle:jade` treats files ending with `.tpl.jade` a bit differently. Perhaps you could create a `.tag.jade` requirement for jade tag files?

**Comment by baysao** [comment]
Hi guys, check out new update support preprocessor including jade

**Comment by jaylach** [comment]
Oh, I'm so happy to hear this! Definitely going to check it out tonight! 

Thanks!! :+1:

**Comment by bkuri** [comment]
That's great news, although I was unable to update to it normally for some reason:

```
$>meteor update
This project is already at Meteor 1.2.1, the latest release.
Your top-level dependencies are at their latest compatible versions.

The following top-level dependencies were not updated to the very latest
version available:
 * baysao:riot-meteor-data 0.1.0-3 (0.1.0-6 is available)
 * baysao:riot-template-helper 0.1.0-1 (0.1.1-0 is available)
 * baysao:riotjs 2.2.4-1 (2.3.1-4 is available)
```

So I ran the following:
```
$>meteor add baysao:riotjs@2.3.1-4
$>meteor add baysao:riot-meteor-data@0.1.0-6
$>meteor add baysao:riot-template-helper@0.1.1-0
```

Finally, I ran meteor and got the following errors:
```
=> Errors prevented startup:                  
   
   While processing files with baysao:riotjs (for target web.browser):

   ~/.meteor/packages/baysao_riotjs/.2.3.1-4.3ndae8++os+web.browser+web.cordova/plugin.compileRiot.os/npm/compileRiot/node_modules/riot-compiler/dist/compiler.js:71:29:
   Cannot call method 'render' of null
   at _html.jade
   (~/.meteor/packages/baysao_riotjs/.2.3.1-4.3ndae8++os+web.browser+web.cordova/plugin.compileRiot.os/npm/compileRiot/node_modules/riot-compiler/dist/compiler.js:71:29)
   at compileTemplate
   (~/.meteor/packages/baysao_riotjs/.2.3.1-4.3ndae8++os+web.browser+web.cordova/plugin.compileRiot.os/npm/compileRiot/node_modules/riot-compiler/dist/compiler.js:500:12)
   at Object.compile
   (~/.meteor/packages/baysao_riotjs/.2.3.1-4.3ndae8++os+web.browser+web.cordova/plugin.compileRiot.os/npm/compileRiot/node_modules/riot-compiler/dist/compiler.js:524:13)
   at packages/compileRiot/plugin/compile-riot.js:38:1
   at Array.forEach (native)
   at RiotCompiler.processFilesForTarget (packages/compileRiot/plugin/compile-riot.js:4:1)
   
   
   While processing files with baysao:riotjs (for target os.linux.x86_64):

   ~/.meteor/packages/baysao_riotjs/.2.3.1-4.3ndae8++os+web.browser+web.cordova/plugin.compileRiot.os/npm/compileRiot/node_modules/riot-compiler/dist/compiler.js:71:29:
   Cannot call method 'render' of null
   at _html.jade
   (~/.meteor/packages/baysao_riotjs/.2.3.1-4.3ndae8++os+web.browser+web.cordova/plugin.compileRiot.os/npm/compileRiot/node_modules/riot-compiler/dist/compiler.js:71:29)
   at compileTemplate
   (~/.meteor/packages/baysao_riotjs/.2.3.1-4.3ndae8++os+web.browser+web.cordova/plugin.compileRiot.os/npm/compileRiot/node_modules/riot-compiler/dist/compiler.js:500:12)
   at Object.compile
   (~/.meteor/packages/baysao_riotjs/.2.3.1-4.3ndae8++os+web.browser+web.cordova/plugin.compileRiot.os/npm/compileRiot/node_modules/riot-compiler/dist/compiler.js:524:13)
   at packages/compileRiot/plugin/compile-riot.js:38:1
   at Array.forEach (native)
   at RiotCompiler.processFilesForTarget (packages/compileRiot/plugin/compile-riot.js:4:1)
```
Here's a version of the to-do tag in jade, which is what I used to test:
https://gist.github.com/bkuri/1c2852eceead363312d6

I'll try this again tomorrow. Many thanks, @baysao! :+1:

**Comment by bkuri** [comment]
@baysao: I decided to start over forking your `simple-todos-riot-meteor-data` demo and converting it to jade/coffeescript/stylus and using `.tag.coffee` and `.tag.jade` instead of `tasks.tag`. You can check it out here: https://github.com/bkuri/simple-todos-riot-meteor-data

**Comment by baysao** [comment]
@bkuri just update code. please update package and check again.

**Comment by bkuri** [comment]
@baysao: Haven't been able to make it work, unfortunately. I just tried running this again on a clean install:
```
$>meteor update
This project is already at Meteor 1.2.1, the latest release.
Your top-level dependencies are at their latest compatible versions.
                                              
The following top-level dependencies were not updated to the very latest version available:
 * baysao:riot-meteor-data 0.1.0-3 (0.1.0-6 is available)
 * baysao:riot-template-helper 0.1.0-1 (0.1.1-0 is available)
 * baysao:riotjs 2.2.4-1 (2.3.1-22 is available)
                                              
Newer versions of the following indirect dependencies are available:
 * jsx 0.1.6 (0.2.3 is available)             
To update one or more of these packages, pass their names to `meteor update`.
```
```
meteor add baysao:riot-meteor-data@0.1.0-6 baysao:riot-template-helper@0.1.1-0 baysao:riotjs@2.3.1-22  
Currently using baysao:riot-meteor-data without any version constraint.            
The version constraint will be changed to 0.1.0-6.
Currently using baysao:riot-template-helper without any version constraint.
The version constraint will be changed to 0.1.1-0.
Currently using baysao:riotjs without any version constraint.
The version constraint will be changed to 2.3.1-22.
                                              
Changes to your project's package version selections:
                                              
baysao:riot-meteor-data      upgraded from 0.1.0-3 to 0.1.0-6
baysao:riot-template-helper  upgraded from 0.1.0-1 to 0.1.1-0
baysao:riotjs                upgraded from 2.2.4-1 to 2.3.1-22
jsx                          upgraded from 0.1.6 to 0.2.3
meteorhacks:async            added, version 1.0.0

                                              
baysao:riot-meteor-data: Riotjs mixin for reactively tracking Meteor data
baysao:riot-template-helper: Use Riot components in native Meteor templates
baysao:riotjs: A React- like, 2.5K user interface library
```
```
$>meteor
=> Started proxy.
=> Started MongoDB.
W20151119-22:38:34.274(-6)? (STDERR) 
W20151119-22:38:48.467(-6)? (STDERR)          
W20151119-22:38:48.468(-6)? (STDERR) /home/bk/.meteor/packages/meteor-tool/.1.1.10.1aanmm2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151119-22:38:48.468(-6)? (STDERR)                                            throw(ex);
W20151119-22:38:48.468(-6)? (STDERR)                                                  ^
W20151119-22:38:48.486(-6)? (STDERR) TypeError: Cannot call method 'mixin' of undefined
W20151119-22:38:48.486(-6)? (STDERR)     at simple-todos.coffee:2:6
W20151119-22:38:48.486(-6)? (STDERR)     at simple-todos.coffee:1:1
W20151119-22:38:48.488(-6)? (STDERR)     at /run/media/bk/0378110d-2574-4da5-9118-13ff90196dc7/source/todos-riot-jade-coffee/.meteor/local/build/programs/server/boot.js:242:10
W20151119-22:38:48.488(-6)? (STDERR)     at Array.forEach (native)
W20151119-22:38:48.488(-6)? (STDERR)     at Function._.each._.forEach (/home/bk/.meteor/packages/meteor-tool/.1.1.10.1aanmm2++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20151119-22:38:48.488(-6)? (STDERR)     at /run/media/bk/0378110d-2574-4da5-9118-13ff90196dc7/source/todos-riot-jade-coffee/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```

**Comment by baysao** [comment]
@bkuri i have some mistake on define preprocessor. Now i fixed it. Please try again and tell me if it ok.

**Comment by bkuri** [comment]
Still no dice after updating everything and integrating the separate coffee file to the main tag file. Here's some console output:
```
$>meteor add baysao:riot-meteor-data baysao:riot-preprocessor baysao:riot-template-helper baysao:riotjs

Changes to your project's package version selections:

baysao:riot-meteor-data+      added, version 0.1.0-6
baysao:riot-preprocessor      added, version 2.3.1-16
baysao:riot-template-helper+  added, version 0.1.1-0
baysao:riotjs+                added, version 2.3.1-31
jsx                           added, version 0.2.3
meteorhacks:async             added, version 1.0.0


+ In order to resolve constraints, we had to use experimental versions of these packages.

baysao:riot-meteor-data: Riotjs mixin for reactively tracking Meteor data
baysao:riot-preprocessor: Riot PreProcessor
baysao:riot-template-helper: Use Riot components in native Meteor templates
baysao:riotjs: riotjs preprocessor
```
```
$>meteor
[[[[[./todos-riot-jade-coffee]]]]]

=> Started proxy.
=> Started MongoDB.
=> Creating container package for npm modules

-> npm support has been initialized.
-> please start your app again.
```
```
$>meteor
[[[[[./todos-riot-jade-coffee]]]]]

=> Started proxy.
=> Started MongoDB.
compileRiot: updating npm dependencies -- riot-compiler, coffee-script, jade...

Changes to your project's package version selections:

baysao:riotjs-preprocessor-init  added, version 0.1.0-1

=> Errors prevented startup:
   
   While determining active plugins:
   error: conflict: two packages included in the app
   (baysao:riotjs-preprocessor-init and baysao:riot-preprocessor) are both
   trying to handle *.tag
   error: conflict: two packages included in the app
   (baysao:riotjs-preprocessor-init and baysao:riot-preprocessor) are both
   trying to handle *.tag.jade
   
   While determining active plugins:
   error: conflict: two packages included in the app
   (baysao:riotjs-preprocessor-init and baysao:riot-preprocessor) are both
   trying to handle *.tag
   error: conflict: two packages included in the app
   (baysao:riotjs-preprocessor-init and baysao:riot-preprocessor) are both
   trying to handle *.tag.jade
   
=> Your application has errors. Waiting for file change.
```

**Comment by baysao** [comment]
@bkuri due to mixing new and old data structure cause errors. Try to remove all extras file and install again.
In detail, remove lines in `.meteor/packages`
`baysao:riotjs`
`baysao:riotjs-preprocessor-init`
`packages/baysao:riot-preprocessor`
 Remove  directories
`packages/baysao:riot-preprocessor` 
`packages/baysao:riotjs-preprocessor-init`
And install `baysao:riotjs` again.
I saw warning `Warning: missing space before text for line 5 of jade file "undefined"`, i think it's related to missing something in your `jade` file.

**Comment by bkuri** [comment]
@baysao the good news is that now meteor runs without errors. The bad news is that I can't see the riot component on the screen: http://screencloud.net/v/q0rg

I decided to remove the inline coffeescript for now and simply copy+paste the JS from your riotjs demo. That did remove the `Warning: missing space before text for line 5 of jade file "undefined"` warning, but nothing happened after that.

I just pushed everything if you want to take a closer look.

**Comment by baysao** [comment]
@bkuri actually compillation of `jade` file show errors, but not show in screen. So i just modify code to print errors message in compilation process. Try to remove `packages/baysao:riotjs-preprocessor-init` files , remove `baysao:riotjs` and `baysao:riotjs-preprocessor-init` in `.meteor/packages` and install `baysao:riotjs` again. you will see errors.

**Comment by bkuri** [comment]
Just tried doing the above a couple of times but I see no changes. No errors, no rendering, etc. Odd...

**Comment by baysao** [comment]
@bkuri. I think you still not get the latest `baysao:riotjs` packages.
Have you try to delete directory`packages/baysao:riotjs-preprocessor-init` (because `baysao:riotjs` still not overwrite it with new content in `baysao:riotjs` package currently) and remove all lines (or comment out) with prefix `baysao:*` packages (that should let meteor remove those packages). After that, you should have a clean project :D, try to uncomment in `.meteor/packages` or install again those packages will let you update newest packages. 
I got error like this
```
{ [SyntaxError: Jade:7
    5|     this.getMeteorData = function() {
    6|       var tasks;
  > 7|       if (Session.get("hideCompleted")) {
    8|         // If hide completed is checked, filter tasks
    9|         tasks = Tasks.find({checked: {$ne: true}}, {sort: {createdAt: -1}}).fetch();
    10|       } else {

```
But i dont use jade, i jade not accept `{` or `}`. 
One more think, in new version `baysao:riotjs`, i change the extension of `jade` preprocessor to `.jade.tag` instead of `.tag.jade` due to conflict with `dalgard:jade` in process `.jade` file.
Try again and let me know :)
